import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Logo from '../src/assets/images/logo/logo.png'

const Home: NextPage = () => {
  const route = useRouter()
  useEffect(() => {
    const token = localStorage.getItem('access_token')
    const role = localStorage.getItem('role')

    if (token) {
      if (role === 'admin') {
        route.push('/dashboard/admin/home')
      }

      if (role === 'member') {
        route.push('/dashboard/member/home')
      }
    }

  }, [])
  return (
    <div className='h-screen'>
      <Head>
        <title>Master Community Online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full">
        <div className=" border-b-2 border-gray-100 p-4 flex justify-between">
          <Image
            src={Logo}
            width={100}
            height={50}
            className="object-cover"
          />

          <div
            className="w-24  flex items-center justify-center rounded-md bg-yellow-300 font-bold cursor-pointer"
            onClick={() => route.push('/auth/login')}
          >
            Login
          </div>
        </div>
        <p className="text-2xl font-bold text-center">Master Online Community</p>
      </div>

    </div>
  )
}

export default Home
